#!/bin/bash

UMASK=`umask`
umask 0022
 
read oldrev newrev refname
 
REPOSITORY="$(pwd | sed 's/\/hooks//')"
BRANCH=$( echo "${refname}" | sed -n 's!^refs/heads/!!p' )
SSFIREWALL=/etc/ssfirewall

IPT_SAVE=/sbin/iptables-save
NOW=$(date +%Y%m%d%H%M%S)

# master branch, as defined by git, is production
if [[ "${BRANCH}" == "master" ]]; then
    echo "Updating ${SSFIREWALL}"
    if [ -d "${SSFIREWALL}" ]; then
		echo "---------------------------------------------------"
		echo "Iussed commands:"
		echo "  cd ${SSFIREWALL}; git fetch --all; git reset --hard origin/${BRANCH}"
		echo "  ${IPT_SAVE} > ${SSFIREWALL}/iptables.rules.${NOW}"
		echo "  /bin/bash ${SSFIREWALL}/iptables-host-basic.sh"
		echo "---------------------------------------------------"
		cd ${SSFIREWALL}
		unset GIT_DIR
		git fetch --all
		git reset --hard origin/${BRANCH}
		exec git-update-server-info
		sudo ${IPT_SAVE} > ${SSFIREWALL}/iptables.rules.${NOW}
		sudo /bin/bash ${SSFIREWALL}/iptables-host-basic.sh
	else
		echo "FATAL: directory ${SSFIREWALL} douen't exist."
		exit 1
	fi
fi

umask $UMASK
exit 0
